# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mpTerminal.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(616, 614)
        MainWindow.setIconSize(QtCore.QSize(512, 512))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 616, 22))
        # self.menubar.setGeometry(QtCore.QRect(0, 0, 516, 32))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuAction = QtWidgets.QMenu(self.menubar)
        self.menuAction.setObjectName("menuAction")
        self.menuSend = QtWidgets.QMenu(self.menubar)
        self.menuSend.setObjectName("menuSend")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setCheckable(False)
        self.actionExit.setShortcutContext(QtCore.Qt.WidgetShortcut)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setCheckable(False)
        self.actionNew.setObjectName("actionNew")
        self.actionClear = QtWidgets.QAction(MainWindow)
        self.actionClear.setObjectName("actionClear")
        self.actionReset_port = QtWidgets.QAction(MainWindow)
        self.actionReset_port.setObjectName("actionReset_port")
        self.actionPortInfo = QtWidgets.QAction(MainWindow)
        self.actionPortInfo.setObjectName("actionPortInfo")
        self.actionsss = QtWidgets.QAction(MainWindow)
        self.actionsss.setObjectName("actionsss")
        self.actionsss_2 = QtWidgets.QAction(MainWindow)
        self.actionsss_2.setObjectName("actionsss_2")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuAction.addAction(self.actionClear)
        self.menuAction.addAction(self.actionReset_port)
        self.menuAction.addAction(self.actionPortInfo)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAction.menuAction())
        self.menubar.addAction(self.menuSend.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuFile.setTitle(_translate("MainWindow", "&File"))
        self.menuHelp.setTitle(_translate("MainWindow", "&Help"))
        self.menuAction.setTitle(_translate("MainWindow", "&Action"))
        self.menuSend.setTitle(_translate("MainWindow", "Send"))
        self.actionExit.setText(_translate("MainWindow", "Quit"))
        self.actionExit.setToolTip(_translate("MainWindow", "Quit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionClear.setText(_translate("MainWindow", "Clear"))
        self.actionReset_port.setText(_translate("MainWindow", "Reset port"))
        self.actionPortInfo.setText(_translate("MainWindow", "Port Info"))
        self.actionsss.setText(_translate("MainWindow", "sss"))
        self.actionsss_2.setText(_translate("MainWindow", "sss"))
